[package]
name = "flow-rust-sdk"
version = "0.5.9"
edition = "2018"

[dependencies]
tonic = "0.5"
prost = "0.8"
hex = "0.4.3"
rlp = "0.5.1"
bytes = { version = "1", features = ["serde"] }
serde-rlp = "0.1.4"
serde = { version = "1.0", features = ["derive"] }
rand_core = "0.6.3"
p256 = {git = "https://github.com/MarshallBelles/elliptic-curves.git", branch = "master", features= ["ecdsa"]}

[patch.crates-io]
ecdsa = { git = "https://github.com/RustCrypto/signatures.git" }
elliptic-curve = { git = "https://github.com/RustCrypto/traits.git" }

[build-dependencies]
tonic-build = "0.5"