[package]
name = "flow-rust-sdk"
version = "0.4.4"
edition = "2018"

[dependencies]
tonic = "0.5"
prost = "0.8"
hex = "0.4.3"
p256 = {version = "0.9.0", features= ["ecdsa"]}
rlp = "0.5.1"
bytes = "1.1.0"
serde-rlp = "0.1.4"
serde = { version = "1.0", features = ["derive"] }
rand_core = "0.6.3"

[build-dependencies]
tonic-build = "0.5"