name: Rust

on:
  push:
    branches: [ test, develop, release ]
  pull_request:
    branches: [ test, develop, release ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
      env:
        SERVICE_ACCT: ${{ secrets.TESTNET_1_ADDRESS }}
        PRIV_K: ${{ secrets.TESTNET_1_PRIVATE_KEY }}
        PUB_K: ${{ secrets.TESTNET_1_PUBLIC_KEY }}
